training_pipline_config:
  pipeline_name: housing
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_url: https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing
  tgz_download_dir: tgz_sata
  ingested_dir: ingested_data
  raw_data_dir: row_data
  ingested_train_dir: train
  ingested_test_dir: test

data_validation_config:
  schema_file_path: schema.yaml

data_transformation_config:
  add_bedroom_per_room: true
  transform_train_dir: train
  transformed_dir: transformed_data
  transformed_test_dir: test
  preprocessed_dir: preprocessed
  preprocessed_object_file_path: preprocessed.pkl

model_trainer_config:
  trained_model_model_dir: trained_model
  model_file_name: model.pkl
  base_accuracy: 0.6

model_pusher)config:
  model_export_dir: saved_models